### ISSUE TITLE
Buttons

### ISSUE THREAD

**Issue by natkiypie** [osu-cascades/bridges#4]
There are buttons in the card containers. Is it okay to use buttons as links? Also, is it okay to use GH issues to ask simple questions like this? Or is it generally used to assign tasks?

**Comment by ybakos** [comment]
Use `a` if there is a destination to another page, and `button` for other interactive cases. See the beginning of this: https://bitsofco.de/anchors-vs-buttons/

**Comment by ybakos** [comment]
So it seems in our case they'd be links, that use the bootstrap btn class, etc to look like buttons.

**Comment by ybakos** [comment]
Out of date.
